//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMPRestApi.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misper_Extended
    {
        public int ID { get; set; }
        public string UniqueID { get; set; }
        public byte[] image { get; set; }
        public string Is_Dangerous { get; set; }
        public string TwitterName { get; set; }
        public string FacebookName { get; set; }
        public string InstagramName { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual misper_ misper_ { get; set; }
    }
}
