//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMPRestApi.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeopleTag()
        {
            this.PeopleTags1 = new HashSet<PeopleTag>();
        }
    
        public int Id { get; set; }
        public int TagID { get; set; }
        public string Unique_ID { get; set; }
    
        public virtual misper_ misper_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeopleTag> PeopleTags1 { get; set; }
        public virtual PeopleTag PeopleTag1 { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
