//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMPRestApi.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneData
    {
        public int ID { get; set; }
        public int LocationID { get; set; }
        public string DeviceID { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
