//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMPRestApi.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public int ID { get; set; }
        public string Unique_id { get; set; }
        public long TweetID { get; set; }
        public System.DateTime TweetDate { get; set; }
    
        public virtual misper_ misper_ { get; set; }
    }
}
